# Generated by Django 5.1 on 2024-08-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=9)),
                ('ano', models.DateField()),
            ],
        ),
    ]
